In [9]:
import numpy as np

In [11]:
def relu(x):
    return np.maximum(0,x)

In [13]:
relu(10)

10

In [15]:
relu(-10)

0

In [21]:
relu(np.array([-1,0,1,2]))

array([0, 0, 1, 2])

In [23]:
def leaky_relu(x, alpha= 0.01):
    return np.where(x > 0, x , x * alpha)

In [25]:
leaky_relu(-1)

array(-0.01)

In [27]:
leaky_relu(np.array([-1,0,1,2]))

array([-0.01,  0.  ,  1.  ,  2.  ])

In [29]:
leaky_relu(-5)

array(-0.05)

In [31]:
def elu(x, alpha=1.0):
    return np.where(x > 0, x, alpha * (np.exp(x) - 1))

In [33]:
elu(5)

array(5.)

In [35]:
elu (np.array([-1,0,1,2]))

array([-0.63212056,  0.        ,  1.        ,  2.        ])

In [37]:
def sigmoid(x):
    return 1 / (1+ np.exp(x))

In [39]:
sigmoid(np.array([-1,0,1,2]))

array([0.73105858, 0.5       , 0.26894142, 0.11920292])

In [41]:
def softmax(x):
    e_x = np.exp(x- np.max(x))
    return e_x / e_x.sum (axis= 0)

In [43]:
proba = softmax(np.array([-1,0,1,2]))
proba

array([0.0320586 , 0.08714432, 0.23688282, 0.64391426])

In [45]:
proba = softmax(np.array([2,1,0.5]))
proba

array([0.62853172, 0.2312239 , 0.14024438])

In [47]:
sum(proba)

1.0

In [55]:
def swish(x, beta=1.0):
    return x * sigmoid(beta * x)

In [57]:
swish(5)

0.03346425462142428

In [59]:
swish(np.array([-1,0,1,2]))

array([-0.73105858,  0.        ,  0.26894142,  0.23840584])

In [61]:
def linear(x):
    return x

In [63]:
linear(10)

10

In [65]:
linear(-10)

-10

In [67]:
def tanh(x):
    return np.tanh(x)

In [69]:
tanh(10)

0.9999999958776927

In [71]:
tanh(-10)

-0.9999999958776927

In [73]:
import math

In [75]:
def sigmoid (z):
    return 1 / (1+ math.exp(-z))

In [77]:
def feedforword(weights,bias,inputs):
    total = sum(w * x for w, x in zip(weights,inputs)) + bias
    return sigmoid(total)

In [79]:
def classify(output , threshold=0.5):
    return 1 if output >= threshold else 0