In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('shoe.csv')

In [3]:
df.head()

size(cm) class(y)
0     9.500   Female
1    10.125     Male
2    10.410     Male
3     9.810   Female
4    11.050     Male

In [4]:
df.shape

(40, 2)

In [5]:
df['class(y)'].value_counts()

class(y)
Male      22
Female    18
Name: count, dtype: int64

#Label Encoder

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() 

In [7]:
df['class(y)'] = le.fit_transform(df[['class(y)']])
df.head()

size(cm)  class(y)
0     9.500         0
1    10.125         1
2    10.410         1
3     9.810         0
4    11.050         1

In [12]:
df.shape

(40, 2)

In [13]:
x=df.drop('class(y)', axis=1)

In [14]:
y=df[['class(y)']]

In [15]:
x.head()

size(cm)
0     9.500
1    10.125
2    10.410
3     9.810
4    11.050

In [16]:
y.head()

class(y)
0         0
1         1
2         1
3         0
4         1

#Logistic Regression

In [17]:
from sklearn.linear_model import LogisticRegression


In [18]:
reg = LogisticRegression()

In [19]:
reg.fit(x,y)

LogisticRegression()

In [20]:
reg.coef_

array([[2.62700105]])

In [21]:
reg.intercept_

array([-26.18202542])

In [23]:
import numpy as np
np.array(df['class(y)'])

array([0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1])

In [24]:
reg.predict(x)

array([0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0])

In [25]:
x.head()

size(cm)
0     9.500
1    10.125
2    10.410
3     9.810
4    11.050

In [26]:
reg.predict_proba(x)

array([[0.7730327 , 0.2269673 ],
       [0.39738803, 0.60261197],
       [0.23774988, 0.76225012],
       [0.60136241, 0.39863759],
       [0.05487101, 0.94512899],
       [0.89519741, 0.10480259],
       [0.79524978, 0.20475022],
       [0.17003549, 0.82996451],
       [0.66236362, 0.33763638],
       [0.69666466, 0.30333534],
       [0.59504837, 0.40495163],
       [0.23302194, 0.76697806],
       [0.357297  , 0.642703  ],
       [0.07737522, 0.92262478],
       [0.17757917, 0.82242083],
       [0.11860619, 0.88139381],
       [0.46492641, 0.53507359],
       [0.52395788, 0.47604212],
       [0.29398963, 0.70601037],
       [0.16274887, 0.83725113],
       [0.38177164, 0.61822836],
       [0.83473521, 0.16526479],
       [0.88221925, 0.11778075],
       [0.13921733, 0.86078267],
       [0.71305649, 0.28694351],
       [0.21477057, 0.78522943],
       [0.29947158, 0.70052842],
       [0.09833563, 0.90166437],
       [0.21923404, 0.78076596],
       [0.11860619, 0.88139381],
       [0.